<?php

use Drupal\Core\Routing\RouteMatchInterface;


/**
 * @file
 * Hooks and functionality for Drupal API module
 */

/**
 * Implements hook_help().
 */
function drupal_api_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.drupal_api':
      $output = '';
      $output .= '<h3>About Drupal API Module</h3>';
      $output .= '<p>Provide a block to see top active issue for a project mantained at <a href="https://www.drupal.org">Drupal.org</a></p>';
      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function drupal_api_theme() {

  $theme['top_issues_block'] = [
    'variables' => [
      'project_name' => NULL,
      'items' => NULL,
      'data' => NULL,
    ],
    'template' => 'top-issues-block',
  ];

  $theme['top_issues_page'] = [
    'variables' => [
      'block' => NULL,
    ],
    'template' => 'top-issues-page',
  ];

  return $theme;
}