<?php

/**
 * @file
 * Provides a variant entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function variant_theme() {
  return [
    'variant' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for variant templates.
 *
 * Default template: variant.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the variant information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_variant(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
