<?php

/**
 * @file
 * Provides a marvel tag entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function marvel_tag_theme() {
  return [
    'marvel_tag' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for marvel tag templates.
 *
 * Default template: marvel-tag.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the marvel tag information
 *     and any fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_marvel_tag(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
