<?php

/**
 * @file
 * Provides a marvel deck entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function marvel_deck_theme() {
  return [
    'marvel_deck' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for marvel deck templates.
 *
 * Default template: marvel-deck.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the marvel deck
 *   information and any fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_marvel_deck(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
