<?php

/**
 * @file
 * Provides a marvel card entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function marvel_card_theme() {
  return [
    'marvel_card' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for marvel card templates.
 *
 * Default template: marvel-card.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the marvel card information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_marvel_card(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
