#!/bin/bash

## #ddev-generated
## Description: Export the configuration of Drupal.
## Usage: cex
## Example: ddev cex

# This can't work unless you have a solr service,
# See https://ddev.readthedocs.io/en/stable/users/extend/additional-services/

drush config:export
