#!/bin/bash

## #ddev-generated
## Description: Import the configuration and clear the cache of Drupal.
## Usage: cim
## Example: ddev cim

# This can't work unless you have a solr service,
# See https://ddev.readthedocs.io/en/stable/users/extend/additional-services/

drush config:import
drush cache:rebuild
