#!/bin/bash

## #ddev-generated
## Description: Clear the cache of Drupal.
## Usage: cr
## Example: ddev cr

# This can't work unless you have a solr service,
# See https://ddev.readthedocs.io/en/stable/users/extend/additional-services/

drush cache:rebuild
